train:
  _target_: src.iris.dataset.EpisodesDatasetRamMonitoring
  max_ram_usage: 30G
  name: train_dataset
test:
  _target_: src.iris.dataset.EpisodesDataset
  max_num_episodes: null
  name: test_dataset
